spring:
  application:
    name: course-gateway
server:
  port: 9000
eureka:
#  instance:
#    hostname: localhost
  client:
#    #    fetch-registry 获取注册表，不需要同步其他节点数据
#    fetch-registry: false
#    #    register-with-eureka 是否将自己注册到eureka server 默认是true
#    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  prefix: /course
  routes:
    course-list:
      path: /list/**
      service-id: course-list
    course-price:
      path: /price/**
      service-id: course-price